# Generated by Django 6.1.1 on 2026-09-28 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backstage", "0006_image_type_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identifies the block when adding it to pages.",
                        max_length=255,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("text_image", "Text and image"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="HTML. Used by text, and text and image, blocks.",
                    ),
                ),
                (
                    "background_colour",
                    models.CharField(
                        blank=True,
                        help_text="#rrggbb; leave blank for the theme's colour.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Enter a colour as #rrggbb, e.g. #7a1f2b.",
                            )
                        ],
                    ),
                ),
                (
                    "text_colour",
                    models.CharField(
                        blank=True,
                        help_text="#rrggbb; leave blank for the theme's colour.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Enter a colour as #rrggbb, e.g. #7a1f2b.",
                            )
                        ],
                    ),
                ),
                (
                    "image_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("full", "Full width"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("text_left", "Text left, image right"),
                            ("image_left", "Image left, text right"),
                            ("image_top", "Image top, text bottom"),
                        ],
                        default="text_left",
                        help_text="Used by text and image blocks.",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks",
                        to="backstage.image",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.block"
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "blocks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pages",
                        through="home.PageBlock",
                        to="home.block",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="pageblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.webpage"
            ),
        ),
    ]
