# Generated by Django 6.1.1 on 2026-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="block",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
