# Generated by Django 6.1.1 on 2026-09-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0006_image_type_logo"),
        ("home", "0002_block_title_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="production",
            field=models.ForeignKey(
                blank=True,
                help_text="Cast list blocks show this production's cast (and its default image if no image is chosen).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="backstage.production",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="layout",
            field=models.CharField(
                choices=[
                    ("text_left", "Text left, image right"),
                    ("image_left", "Image left, text right"),
                    ("image_top", "Image top, text bottom"),
                ],
                default="text_left",
                help_text="Used by text and image, and cast list, blocks (the cast list takes the text's place).",
                max_length=20,
            ),
        ),
    ]
