# Generated by Django 6.1.1 on 2026-10-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_block_cast_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                    ("hero_image", "Hero image"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
