# Generated by Django 6.1.1 on 2026-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_block_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="HTML. Used by text, text and image, and hero image (optional) blocks.",
            ),
        ),
    ]
