# Generated by Django 6.1.1 on 2026-10-01 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_block_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="background_colour",
            field=models.CharField(
                blank=True,
                help_text="#rrggbb; leave blank for the theme's colour.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Enter a colour as #rrggbb, e.g. #7a1f2b."
                    )
                ],
            ),
        ),
    ]
