# Generated by Django 6.1.1 on 2026-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_webpage_background_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                    ("hero_image", "Hero image"),
                    ("split", "Split text and image"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="layout",
            field=models.CharField(
                choices=[
                    ("text_left", "Text left, image right"),
                    ("image_left", "Image left, text right"),
                    ("image_top", "Image top, text bottom"),
                ],
                default="text_left",
                help_text="Used by text and image, split, and cast list, blocks (the cast list takes the text's place).",
                max_length=20,
            ),
        ),
    ]
