# Generated by Django 6.1.1 on 2026-10-01 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_block_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Where clicking the image goes: a web address, or a path on this site such as /page/about/. Used by text and image, and split, blocks.",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(https?://\\S+|/\\S*)$",
                        "Enter a full web address (https://...) or a path on this site, e.g. /page/about/.",
                    )
                ],
                verbose_name="Image link",
            ),
        ),
    ]
