# Generated by Django 6.1.1 on 2026-10-02 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0009_production_events"),
        ("home", "0008_block_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                    ("hero_image", "Hero image"),
                    ("split", "Split text and image"),
                    ("columns_2", "Two columns"),
                    ("columns_3", "Three columns"),
                    ("columns_4", "Four columns"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BlockColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("text", models.TextField(blank=True, help_text="HTML.")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Where clicking the image goes: a web address, or a path on this site such as /page/about/.",
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(https?://\\S+|/\\S*)$",
                                "Enter a full web address (https://...) or a path on this site, e.g. /page/about/.",
                            )
                        ],
                        verbose_name="Image link",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="home.block",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="block_columns",
                        to="backstage.image",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
