# Generated by Django 6.1.1 on 2026-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_block_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="equal_height",
            field=models.BooleanField(
                default=False,
                help_text="Columns blocks: draw each column in a box, all as tall as the tallest one.",
                verbose_name="Equal height columns",
            ),
        ),
    ]
