# Generated by Django 6.1.1 on 2026-10-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_block_equal_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="separate_columns",
            field=models.BooleanField(
                default=False,
                help_text="Columns blocks: each column is its own card with a gap between, instead of sharing the block's card.",
                verbose_name="Separate columns",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="equal_height",
            field=models.BooleanField(
                default=False,
                help_text="Columns blocks: make all the columns as tall as the tallest one (they are drawn in boxes, unless separate).",
                verbose_name="Equal height columns",
            ),
        ),
    ]
