# Generated by Django 6.1.1 on 2026-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_block_separate_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="flush_images",
            field=models.BooleanField(
                default=False,
                help_text="Columns blocks: images run to the edges of their card, with the text padded underneath. For separate columns, or equal height columns (where the columns are in cards or boxes).",
                verbose_name="Images with no margin",
            ),
        ),
    ]
