# Generated by Django 6.1.1 on 2026-10-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_block_flush_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockcolumn",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Shown as a heading between the image and the text.",
                max_length=255,
            ),
        ),
    ]
