# Generated by Django 6.1.1 on 2026-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_blockcolumn_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="match_image_heights",
            field=models.BooleanField(
                default=False,
                help_text="Columns blocks: every image is as tall as the shortest one; the taller images are cropped to match.",
                verbose_name="Images the same height",
            ),
        ),
    ]
