# Generated by Django 6.1.1 on 2026-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_block_match_image_heights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                    ("hero_image", "Hero image"),
                    ("split", "Split text and image"),
                    ("columns_2", "Two columns"),
                    ("columns_3", "Three columns"),
                    ("columns_4", "Four columns"),
                    ("auditions", "Auditions"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="HTML. Used by text, text and image, hero image (optional) and auditions (optional) blocks.",
            ),
        ),
    ]
