# Generated by Django 6.1.1 on 2026-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_block_auditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockcolumn",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Shown centred at the top of the column, above the image.",
                max_length=255,
            ),
        ),
    ]
