# Generated by Django 6.1.1 on 2026-10-04 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_blockcolumn_title_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="fade_in_seconds",
            field=models.FloatField(
                default=5,
                help_text="Hero image blocks: how long the image, subtitle and text take to fade in. 0 for no fade.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Fade-in time (seconds)",
            ),
        ),
    ]
