# Generated by Django 6.1.1 on 2026-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_block_fade_in_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                    ("hero_image", "Hero image"),
                    ("split", "Split text and image"),
                    ("columns_2", "Two columns"),
                    ("columns_3", "Three columns"),
                    ("columns_4", "Four columns"),
                    ("auditions", "Auditions"),
                    ("promotion", "Promotion"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
