# Generated by Django 6.1.1 on 2026-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_block_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="diary_show",
            field=models.CharField(
                choices=[
                    ("auditions", "Auditions"),
                    ("performances", "Performances"),
                    ("both", "Auditions and Performances"),
                ],
                default="both",
                help_text="Diary blocks: which events to list.",
                max_length=20,
                verbose_name="Show",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("text_image", "Text and image"),
                    ("cast", "Cast list"),
                    ("hero_image", "Hero image"),
                    ("split", "Split text and image"),
                    ("columns_2", "Two columns"),
                    ("columns_3", "Three columns"),
                    ("columns_4", "Four columns"),
                    ("auditions", "Auditions"),
                    ("promotion", "Promotion"),
                    ("diary", "Diary"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
