# Generated by Django 6.1.1 on 2026-10-05 11:19

from django.db import migrations, models


def to_new_choices(apps, schema_editor):
    """The old options were auditions, performances and both: performances and both are now upcoming stage plays."""
    apps.get_model("home", "Block").objects.filter(diary_show__in=["performances", "both"]).update(diary_show="upcoming_stage")


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_block_diary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="diary_show",
            field=models.CharField(
                choices=[
                    ("recent_radio", "Recent radio plays"),
                    ("upcoming_radio", "Upcoming radio plays"),
                    ("upcoming_stage", "Upcoming stage plays"),
                    ("auditions", "Auditions"),
                ],
                default="upcoming_stage",
                help_text="Diary blocks: which events to list.",
                max_length=20,
                verbose_name="Show",
            ),
        ),
        migrations.RunPython(to_new_choices, migrations.RunPython.noop),
    ]
