# Generated by Django 6.1.1 on 2026-10-05 11:22

import home.models
from django.db import migrations, models


def copy_show(apps, schema_editor):
    """Each block's one choice becomes a list of one."""
    Block = apps.get_model("home", "Block")
    for block in Block.objects.all():
        block.diary_shows = [block.diary_show]
        block.save(update_fields=["diary_shows"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_diary_show_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="diary_shows",
            field=models.JSONField(
                blank=True,
                default=home.models.default_diary_shows,
                help_text="Diary blocks: which kinds of event to list (a list of DiaryShow values).",
                verbose_name="Show",
            ),
        ),
        migrations.RunPython(copy_show, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="block",
            name="diary_show",
        ),
    ]
