# Generated by Django 6.1.1 on 2026-10-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="home.webpage",
            ),
        ),
    ]
