# Generated by Django 6.1.1 on 2026-09-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="people", to="backstage.role"
            ),
        ),
    ]
