# Generated by Django 6.1.1 on 2026-09-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0002_person_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["name"]},
        ),
    ]
