# Generated by Django 6.1.1 on 2026-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0003_role_ordering"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="writer",
        ),
        migrations.AddField(
            model_name="production",
            name="broadcast_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="listen_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
