# Generated by Django 6.1.1 on 2026-09-28 10:08

from django.db import migrations, models
from django.db.models import Min


def mark_earliest_images_default(apps, schema_editor):
    """Each production with images gets its earliest image as the default."""
    ProductionImage = apps.get_model("backstage", "ProductionImage")
    earliest = ProductionImage.objects.values("production").annotate(first=Min("id")).values("first")
    ProductionImage.objects.filter(pk__in=earliest).update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0004_remove_production_writer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionimage",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="productionimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("production",),
                name="one_default_image_per_production",
            ),
        ),
        migrations.RunPython(mark_earliest_images_default, migrations.RunPython.noop),
    ]
