# Generated by Django 6.1.1 on 2026-09-28 10:31

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0005_productionimage_is_default"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="backstage_Image_image_type_ImageType",
        ),
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("base", "Base"),
                    ("audition", "Audition"),
                    ("promotion", "Promotion"),
                    ("gallery", "Gallery"),
                    ("headshot", "Headshot"),
                    ("logo", "Logo"),
                    ("other", "Other"),
                ],
                default="base",
                max_length=9,
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "image_type__in",
                        [
                            "base",
                            "audition",
                            "promotion",
                            "gallery",
                            "headshot",
                            "logo",
                            "other",
                        ],
                    )
                ),
                name="backstage_Image_image_type_ImageType",
            ),
        ),
    ]
