# Generated by Django 6.1.1 on 2026-09-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0006_image_type_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"image_type": "logo"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="backstage.image",
            ),
        ),
    ]
