# Generated by Django 6.1.1 on 2026-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0007_venue_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("audition", "Audition"),
                    ("rehearsal", "Rehearsal"),
                    ("performance", "Performance"),
                    ("other", "Other"),
                ],
                default="performance",
                max_length=20,
            ),
        ),
    ]
