# Generated by Django 6.1.1 on 2026-09-28 18:01

from django.db import migrations, models


def copy_event_links(apps, schema_editor):
    """Keep each production's single event as one of its events."""
    Production = apps.get_model("backstage", "Production")
    for production in Production.objects.exclude(event=None):
        production.events.add(production.event_id)


def copy_first_event_back(apps, schema_editor):
    Production = apps.get_model("backstage", "Production")
    for production in Production.objects.all():
        first = production.events.order_by("id").first()
        if first:
            production.event_id = first.pk
            production.save(update_fields=["event"])


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0008_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="productions", to="backstage.event"
            ),
        ),
        migrations.RunPython(copy_event_links, copy_first_event_back),
        migrations.RemoveField(
            model_name="production",
            name="event",
        ),
    ]
