# Generated by Django 6.1.1 on 2026-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0009_production_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_theme",
                    models.CharField(
                        blank=True,
                        help_text="The theme every visitor sees on the public pages. Blank: Upstage, or Upstage dark if the visitor's device prefers dark.",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "site settings",
            },
        ),
    ]
