# Generated by Django 6.1.1 on 2026-10-04 11:54

import backstage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0011_headshot_resized_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=backstage.fields.HeadshotImageField(
                crop=["middle", "center"],
                force_format=None,
                keep_meta=False,
                quality=90,
                scale=None,
                size=[400, 500],
                upload_to="images/",
            ),
        ),
    ]
