# Generated by Django 6.1.1 on 2026-10-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0012_headshot_size_400x500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("audition", "Audition"),
                    ("rehearsal", "Rehearsal"),
                    ("performance", "Performance"),
                    ("broadcast", "Broadcast"),
                    ("other", "Other"),
                ],
                default="performance",
                max_length=20,
            ),
        ),
    ]
