# Generated by Django 6.1.1 on 2026-10-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0014_broadcast_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="broadcast_datetime",
        ),
    ]
