# Generated by Django 6.1.1 on 2026-10-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0015_remove_production_broadcast_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="publish",
            field=models.CharField(
                choices=[
                    ("not_published", "Not published"),
                    ("published", "Published"),
                    ("promoted", "Promoted"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
    ]
