# Generated by Django 6.1.1 on 2026-10-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0016_event_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
    ]
