# Generated by Django 6.1.1 on 2026-10-05 10:35

import django_enum.fields
from django.db import migrations, models


def base_to_production(apps, schema_editor):
    apps.get_model("backstage", "Image").objects.filter(image_type="base").update(image_type="production")


def production_to_base(apps, schema_editor):
    apps.get_model("backstage", "Image").objects.filter(image_type="production").update(image_type="base")


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0017_remove_event_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="backstage_Image_image_type_ImageType",
        ),
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("production", "Production"),
                    ("audition", "Audition"),
                    ("promotion", "Promotion"),
                    ("gallery", "Gallery"),
                    ("headshot", "Headshot"),
                    ("logo", "Logo"),
                    ("other", "Other"),
                ],
                default="production",
                max_length=10,
            ),
        ),
        migrations.RunPython(base_to_production, production_to_base),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "image_type__in",
                        [
                            "production",
                            "audition",
                            "promotion",
                            "gallery",
                            "headshot",
                            "logo",
                            "other",
                        ],
                    )
                ),
                name="backstage_Image_image_type_ImageType",
            ),
        ),
    ]
