# Generated by Django 6.1.1 on 2026-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0018_rename_image_type_base_production"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Occasional newsletter"
                    ),
                ),
                ("acting", models.BooleanField(default=False, verbose_name="Acting")),
                (
                    "backstage",
                    models.BooleanField(default=False, verbose_name="Backstage roles"),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
