# Generated by Django 6.1.1 on 2026-10-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0019_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="state",
        ),
    ]
