# Generated by Django 6.1.1 on 2026-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0020_remove_production_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="listen_url",
            field=models.URLField(blank=True),
        ),
    ]
