# Generated by Django 6.1.1 on 2026-10-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0023_remove_production_listen_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProduction",
            fields=[
                (
                    "production_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="backstage.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "parent production",
            },
            bases=("backstage.production",),
        ),
        migrations.AddField(
            model_name="production",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent production this is part of: it must be the same type of production",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="backstage.parentproduction",
            ),
        ),
    ]
